= java-mavenmixin-jettyconsole
:_imagesdir: ./
:toc:


This module, for use within link:http://isis.apache.org[Apache Isis] applications, provides a link:https://github.com/odavid/maven-plugins[maven mixin] that can be used to package up a webapp using the link:https://github.com/eirbjo/jetty-console[jetty-console plugin], and to run that webapp using the link:http://maven.apache.org/plugins/maven-antrun-plugin/[AntRun plugin].
This reduces the size of the maven `pom.xml` file for that consuming module; it simply needs to reference _this_ module using the `mixin-maven-plugin`.

The appropriate configuration is included in a `<profile>` which is automatically **ex**cluded in all builds.
This profile can be enabled using a Maven property.


[TIP]
====
For further background on this module, see the original link:http://simplericity.com/2009/11/10/1257880778509.html[blog post].
====



== How to Configure

To configure:

* copy and paste the following into either the `pom.xml` of the consuming module or (better still) the `pom.xml` of the top-level parent of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <mavenmixin-jettyconsole.version>0.0.2</mavenmixin-jettyconsole.version>

    <jetty-console-maven-plugin.version>1.59</jetty-console-maven-plugin.version>
    <maven-antrun-plugin.version>1.8</maven-antrun-plugin.version>
    ...
</properties>
----
+
and: +
+
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            ...
            <plugin>
                <groupId>org.simplericity.jettyconsole</groupId>
                <artifactId>jetty-console-maven-plugin</artifactId>
                <version>${jetty-console-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven-antrun-plugin.version}</version>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
----

* update the following property/ies in the `pom.xml` of the consuming webapp module (with `<packaging>war</packaging>`): +
+
[source,xml]
----
<properties>
    ...
    <jetty-console-maven-plugin.backgroundImage>                                        <!--1-->
        ${basedir}/src/main/jettyconsole/isis-banner.png
    </jetty-console-maven-plugin.backgroundImage>
    <maven-antrun-plugin.jettyconsole.args></maven-antrun-plugin.jettyconsole.args>     <!--2-->
    ...
</properties>
----
<1> (optional) the background image to use
<2> (optional) additional arguments to pass through when running the webapp
+
These properties should be specified in the consuming module.
+
[TIP]
====
A suggested image, `isis-banner.png` can be downloaded https://raw.githubusercontent.com/danhaywood/java-mavenmixin-jettyconsole/master/images/isis-banner.png[here]
====


* add the following to the `pom.xml` of the consuming module: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    <mixin>
                        <groupId>com.danhaywood.mavenmixin</groupId>
                        <artifactId>jettyconsole</artifactId>
                        <version>${mavenmixin-jettyconsole.version}</version>
                    </mixin>
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----

* Specify any mandatory input properties (see above).



== How to use

To generate the runnable jetty-console WAR file, use:

[source,bash]
----
mvn install -Dmavenmixin-jettyconsole
----

This will generate a `xxx-jetty-console.war` file in the `target` directory.

This WAR file can then be run, eg:

[source,bash]
----
cd webapp/target
java -jar xxx-jetty-console.war 
----

Alternatively, the configured AntRun plugin can be used:

[source,bash]
----
mvn -pl webapp antrun:run -Dmavenmixin-jettyconsole
----

Additional arguments can be specified using the `maven-antrun-plugin.jettyconsole.args` system property.
For example:

[source,bash]
----
mvn -pl webapp antrun:run -Dmavenmixin-jettyconsole \
               -Dmaven-antrun-plugin.jettyconsole.args="--headless --port 9090"
----




== Known issues

None currently



== Change Log

* `0.0.2` - updates README for properties and plugin management, shortens property names and profile id
* `0.0.1` - first release




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----



=== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.2 \
              0.0.3-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
git push origin 0.0.2
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
